
include ../calib.mk
include $(ROOT_DIR)/config.mk


UNITTEST_TARGETS = hello test_sys_info

test_sys_info_NAME=test_sys_info
test_sys_info_SRCS=test_sys_info.c
test_sys_info_LIBS=calib.a

hello_NAME=hello
hello_SRCS=hello.c
hello_LIBS=calib.a


include $(ROOT_DIR)/template.mk

